### PR TITLE
Upgrade to Storm 2.3.0 and fix broken links for Storm helm chart source

### PR DESCRIPTION
**Pull request by pavlovic-ivan**
**Intention**

When Storm helm chart landing page is opened in Artifacthub, links to the sources are broken. This PR resolves the issue and it also bumps the version of Storm used. 

**Solution**

Issue is fixed with two points:
- This PR bumps the version of Storm to 2.3.0
- Helm chart list of sources is adapted and version of the chart itself is bumped to 1.1.0

Bumping Storm version to 2.3.0 is done as opportunity to resolve another issue at same time.
Issues in question: 
- resolves: https://github.com/G-Research/charts/issues/62
- fixes: https://github.com/G-Research/charts/issues/59

@stackedsax @jgiannuzzi please take a look. Looking forward to your feedback.

Best regards,
Ivan ✌️

### CODE REVIEW

**Review by stackedsax — APPROVED** [review]
Thanks for fixing this -- hopefully it allows people to use this chart a little more willingly.

**Review by jgiannuzzi — CHANGES_REQUESTED** [review]
Thanks for your PR @pavlovic-ivan!

There is unfortunately an extra `index.yaml` file found in the `storm/storm-1.1.0.tgz` archive. Could you please remove it?

**Comment by pavlovic-ivan** [comment]
@jgiannuzzi certainly

**Comment by pavlovic-ivan** [comment]
@stackedsax @jgiannuzzi file removed

**Review by jgiannuzzi — APPROVED** [review]
LGTM 👍

Thanks for killing two 🐦 with one 🪨, @pavlovic-ivan 👏

**Comment by pavlovic-ivan** [comment]
🙏

**Pull request merged**
