### PR TITLE
Add nodeSelector, serviceAccountName and tolerations for supervisor deployment

### PR DESCRIPTION
**Pull request by diegmonti**
This PR adds `nodeSelector`, `serviceAccountName` and `tolerations` to the supervisor deployment.

### CODE REVIEW

**Review by pavlovic-ivan — APPROVED** [review]
Hi @diegmonti . Thank you for your PR. Looks good to me!

**Comment by pavlovic-ivan** [comment]
@diegmonti would you like to take over maintainership of this repo?

**Comment by diegmonti** [comment]
Thank you for reaching out. After an initial evaluation, my company decided to deploy Apache Storm independently and won't be relying on this Helm chart. As a result, I'm unable to take on maintainership at this time.

**Comment by pavlovic-ivan** [comment]
All right. Thanks for the feedback. Please go ahead and merge the PR!

**Comment by diegmonti** [comment]
I don't have write access to this repository.

**Comment by pavlovic-ivan** [comment]
PR merged. Thank you!

**Pull request merged**
