### PR TITLE
refactor publishing charts - gh-pages

### PR DESCRIPTION
**Pull request by ljubon**
`master` branch PR: https://github.com/G-Research/charts/pull/75

The purpose of this PR is to perform a cleanup over `charts` repo and improve and automate the release process for new charts for all repos across G-Research organization

The file `.github/workflows/scripts/config.json` contains all info for repos and it will be used as a single source of truth for publishing charts.
By default, new packaged charts will be pushed to the `G-Research/charts:gh-pages` branch with an updated `index.yaml`

Current PR support publishing charts in two way:
- invoking a workflow from another repo (e.g G-Research/armada - example below)
   - each repo should have his own `APP_ID` and `APP_PRIVATE_KEY`, instruction for creating a GitHub app is given in file [GITHUB_APP_GUIDE.md](https://github.com/ljubon/charts/blob/master-public/GITHUB_APP_GUIDE.md)
- adding a Helm chart template structure to `master` branch  in a separate folder (e.g current example is `siembol`)

## TODO
- check/confirm which repos should start using new workflow and change accordingly `.github/workflows/scripts/config.json`

## Demo workflows and runs
The development branch is `INTERNAL-master` and `INTERNAL-refactor-gh-pages`
- Storm (ljubon/charts repo) [run ](https://github.com/ljubon/charts/actions/runs/2185612237)and [workflow](https://github.com/ljubon/charts/actions/runs/2185612237/workflow)
- Armada charts example 
    - ljubon/armada [workflow ](https://github.com/ljubon/armada/actions/runs/2185617524/workflow) (invoking push workflow)
    - ljubon/armada [run ](https://github.com/ljubon/armada/runs/6067198718?check_suite_focus=true)(invoking push workflow)
    - ljubon/charts [publishing charts](https://github.com/ljubon/charts/runs/6067202306?check_suite_focus=true)

## Example
Invoking a workflow from another repository:
```yaml
name: Release

on: 
  push:
    tags: 
      - 'v*'

jobs:
  invoke-push:
    uses: G-Research/charts/.github/workflows/invoke-push.yaml@master
    secrets:
      APP_ID: ${{ secrets.APP_ID }} 
      APP_PRIVATE_KEY: ${{ secrets.GH_APP_PEM }}
```

### CODE REVIEW

**Comment by stackedsax** [comment]
Thanks for the PR, @ljubon.  I was curious: it looks like a lot of existing artifacts and chart src files are getting removed in this PR.  Is this the right thing to do?  I can't remember exactly, but I think artifacthub.io will still reference all of those old artifacts even if we remove them.  Is it what we want to do here?

**Comment by ljubon** [comment]
> Thanks for the PR, @ljubon. I was curious: it looks like a lot of existing artifacts and chart src files are getting removed in this PR. Is this the right thing to do? I can't remember exactly, but I think artifacthub.io will still reference all of those old artifacts even if we remove them. Is it what we want to do here?

Hey @stackedsax , good point - as I just checked this now, it shouldn't be a problem in this case - by default `index.yaml` file contains all metadata regarding charts which is crucial for `artifacthub.io`, but anyway I suggest that we should  check (who has access) `artifacthub.io` if it's configured to point to `https://g-research.github.io/charts/` or `https://github.com/G-Research/charts`. 
Per my research, once we move `index.yaml` to `gh-pages` with all charts we should use github pages link for our charts

**Comment by jayofdoom** [comment]
It's probably worth explicitly talking about ordering of this and the `master` PR.  Is there an order you can merge them in where we can insure links don't get broken even for a moment?

**Comment by ljubon** [comment]
> It's probably worth explicitly talking about ordering of this and the `master` PR. Is there an order you can merge them in where we can insure links don't get broken even for a moment?

Thanks for asking that, I've discussed that with Ivan and Marijana - and as far I remember i thInk few thing should happen in parallel
- merging `master `
- merging `gh-pages` with a final update to `index.yaml` as it's important to  get the latest paths and metadata 
(cmd: `helm repo index .` on `gh-pages` branch in root )

technically if someone at the same time tries to pull charts I wouldn't know what would happen, but if any downtime happens it will be in a matter of a few seconds as propagation finishes. Verification will be done after merging it and `artifacthub.io` pickup latest index.yaml and paths to the charts

**Review by jgiannuzzi — APPROVED** [review]

**Pull request merged**
